# Site wide configuration

title:            :-X archcodev - 如果编程语言是汽车
locale:           zh_CN
url:              http://archcodev.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Duke Wong
  avatar: bio-photo.jpg
  bio: "Programming Is A Labor Of Love."
  email: bdw2job@hotmail.com
  disqus-shortname: archcodev
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-42351275-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 236E6D53D4B6131F3F9132395C497D5E
  github: #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
